### ISSUE TITLE
Add TextArea Component

### ISSUE THREAD

**Issue by jkusa** [denali-design/denali-ember#6]
https://denali.design/docs/2/components/fields#textarea

**Comment by willmsn98** [comment]
Should add support for TextArea to InputGroup when it is added.

**Comment by ldkge** [comment]
Are we going to add support for other filed types, like the search field?

**Comment by jkusa** [comment]
@ldkge you can use `search` as a `type` in DenaliInput

**Comment by jkusa** [comment]
closed via #31
